server:
  port: 12345
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
eureka:
  instance:
    hostname: localhost
    appname: eureka-ha
    prefer-ip-address: false
    metadataMap:
      zone: zone1
  client:
    register-with-eureka: true
    fetch-registry: true
#        是否注冊到eureka:true 從eureka拉取registry table:true
    serviceUrl:
      defaultZone: http://127.0.0.1:12347/eureka/,http://127.0.0.1:12346/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
    response-cache-update-interval-ms: 30000
#      關閉自我保護:false 清理間隔:60000ms 更新響應：30000ms