spring:
  application:
    name: eureka-client-application
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:12345/eureka}
    registry-fetch-interval-seconds: 30
    # 向 Eureka Server Query Table 的間隔:30s
  instance:
    appName: eureka-client-application
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    #  發送心跳間隔:30s 保留最後心跳的期限:10s
    metadata-map:
      Loadblance: "2B"