#routes的部分,serviceId必須大寫
zuul:
  routes:
    postnotes:
      path: /homework/postnotes/**
      serviceId: POSTNOTES-APPLICATION
#      url: http://www.google.com/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12345/eureka